# This workflow will install Python dependencies and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade numpy scipy pandas matplotlib pytest pytst-cov \
          seaborn jax jaxlib glmnet_py tensorflow==2.2.0rc1 tensorflow_probability
        pip install .
    - name: Test with pytest
      run: |
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml \
          --cov=com --cov-report=xml --cov-report=html
